name: Build2

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto_full:latest

    permissions:
      contents: write

    env:
      KICAD_LIBRARY: /home/runner/work/ZSWatch-HW/ZSWatch-HW/library

    strategy:
      matrix:
        device_type: [Watch, Sensor]
        include:
          - device_type: Watch
            NewImage: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .
          submodules: recursive

      - name: Dependencies
        run: |
          git clone https://github.com/Kampi/KiCad.git library

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Initialize
        run: |
          mkdir -p docs/images/
          mkdir -p production

      - name: Generate files
        uses: INTI-CMNB/KiBot@v2
        with:
          variant: ['Watch'; 'Sensor']

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device_type }}
          path: |
            production
          if-no-files-found: ignore

      - if: ${{ matrix.NewImage && (github.event.pull_request.merged == true) }}
        name: Update image
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          cp production/${{ matrix.device_type }}/docs/images/PCB_Rendering.png docs/images/Image_Complete.png
          git add docs/images/Image_Complete.png
          git commit -m "Add image from CI/CD action"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          echo https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin ${{ github.base_ref }}
